### ISSUE TITLE
Replication issue

### ISSUE THREAD

**Issue by ibakayoko** [eXist-db/messaging-replication#125]
### Context information
- eXist-db version 
   eXist Version : 3.6.1
   eXist Build : 201802042132
   Git commit : 3be6286

- Extension version
   exist-messaging-replication-0.30.3.jar
   messaging-replication-0.30.3.xar

- ActiveMQ broker version
  activemq-all-5.15.2.jar

- Operating system, 32/64 bit
 Mac OS X 10.11.6 x86_64

- Java version 32/64 bit
1.8.0_131
64-Bit

### Expected bahavior
Document created in the master server in /db/mycollection/ (e.g. using the java client or eXide; login as admin); The document will be automatically replicated to the slave server.

### Actual behavior
Document not replicated to the slave server

Publisher (exist.log)
[exist.log](https://github.com/eXist-db/messaging-replication/files/1695764/exist.log)

Subscriber (exist.log)
[exist.log](https://github.com/eXist-db/messaging-replication/files/1695778/exist.log)

### Steps to reproduce the behavior
1. eXistDB
git clone https://github.com/eXist-db/exist.git
cd exist
git checkout -b release/eXist-3.6.1 origin/release/eXist-3.6.1
./build.sh

2. messaging-Replication
git clone https://github.com/eXist-db/messaging-replication.git
cd messaging-replication
ant setup
#copy the XAR files in exist autodeploy folder
ant install
#copy of jar to exist
cp -a ./build/exist-messaging-replication-0.30.3.jar ../exist/lib/extensions/.

3. ActiveMQ
download http://activemq.apache.org/download.html
extract the archive
copy activemq-all-5.15.2.jar to exist/lib/user/

4. to create to instance of eXistDB
cp -a exist publisher
cp -a exist subscriber

5. Publisher configuration
cd publisher
java -jar start.jar
Click on eXist (icon showing on right to bar)
Click on System Configuration
Change Jetty HTTP Port to 8899
Change Jetty SSL Port to 9443
Click Save

Click on eXist (icon showing on right to bar)
Click on Open Dashboard
login (admin/ )

Master (publisher)
Create collection /db/mycollection/ that shall be monitored for document changes

Create collection /db/system/config/db/mycollection/

Create in there a document collection.xconf and add the following content to the document:

```
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <triggers>
        <trigger class="org.exist.extensions.exquery.restxq.impl.RestXqTrigger"/>

        <trigger class="org.exist.jms.replication.publish.ReplicationTrigger">

            <!-- 
                Class name of the initial context provider, default value for ActiveMQ
                see javax.naming.Context#INITIAL_CONTEXT_FACTORY
            -->
            <parameter name="java.naming.factory.initial" value="org.apache.activemq.jndi.ActiveMQInitialContextFactory"/>

            <!-- 
                URL of the message broker, default value for ActiveMQ 
                see javax.naming.Context#PROVIDER_URL
            --> 
            <parameter name="java.naming.provider.url" value="tcp://localhost:61616"/>

            <!-- 
                Lookup connection factory
                see javax.naming.InitialContext#lookup(String) 
            -->
            <parameter name="connectionfactory" value="ConnectionFactory"/>

            <!--
                Lookup destination (topic)
                see javax.naming.InitialContext#lookup(String) 
            -->
            <parameter name="topic" value="dynamicTopics/eXistdb"/>

            <!--
                Set client identifier for this connection.
                see javax.jms.Connection#setClientID(string)

                [Optional] 
            -->
            <parameter name="client-id" value="1123456789000"/> 

            <!-- 
                Set time-to-live in milliseconds, default value is 0 (unlimited) 
                see javax.jms.MessageProducer#setTimeToLive(long)

                [Optional]
            -->
            <!-- <parameter name="time-to-live" value="0"/> -->

            <!--
                Sets the producer priority, value 0-9 ; default is 4.
                see javax.jms.MessageProducer#setPriority(int)

                [Optional]
            -->
            <!-- <parameter name="priority" value="4"/>-->

        </trigger>
    </triggers>
</collection>
```

Set the correct value for java.naming.provider.url that matches your message broker (ActiveMQ).

Set a unique value for the client-id parameter.

6 - Subscriber configuration

cd subscriber
java -jar start.jar
Click on eXist (icon showing on right to bar)
Click on System Configuration
Change Jetty HTTP Port to 8877
Click Save

Slave (subscriber)
Add a startup trigger to conf.xml:

```
<!--
                    Start JMS listener for listener of the clustering feature. 
                -->
                <trigger 
                    class="org.exist.jms.replication.subscribe.ReceiverStartupTrigger">
                    <!-- 
                        Class name of the initial context provider, default value for ActiveMQ
                        see javax.naming.Context#INITIAL_CONTEXT_FACTORY
                    -->
                    <parameter name="java.naming.factory.initial" 
                        value="org.apache.activemq.jndi.ActiveMQInitialContextFactory"/>
                    
                    <!-- 
                        URL of the message broker, default value for ActiveMQ
                        see javax.naming.Context#PROVIDER_URL
                    -->
                    <parameter name="java.naming.provider.url" 
                        value="tcp://localhost:61616"/>
                    
                    <!-- 
                        Lookup connection factory
                        see javax.naming.InitialContext#lookup(String) 
                    -->
                    <parameter name="connection-factory" value="ConnectionFactory"/>
                    
                    <!--
                        Lookup destination (topic)
                        see javax.naming.InitialContext#lookup(String) 
                    -->
                    <parameter name="destination" 
                                  value="dynamicTopics/eXistdb"/>
                    
                    <!-- 
                        Set the name used to identify this subscription
                        see JMS javax.jms.TopicSession#createDurableSubscriber(Topic,String) 
                    -->
                    <parameter name="subscriber.name" value="SubscriptionId"/>
                    
                    <!-- 
                        Set the client identifier for the connection
                        see JMS javax.jms.Connection#setClientID(String) 
                    -->
                    <parameter name="connection.client-id" value="1123456789"/>
                    
                </trigger>
```
  
Set the correct value for java.naming.provider.url that matches your message broker (ActiveMQ).

Set unique values for client-id and subscriber-name.

Click on eXist (icon showing on right to bar)
Click on Open Dashboard
login (admin/ )

Create the collection /db/mycollection/, this is the collection that receives the documents that are updated in the same collection on the Master server.

Start Applications

1 - ActiveMQ
cd $ACTIVEMQ_HOME
./bin/activemq start

2 - Start Slave
cd $EXISTSLAVE_HOME
./bin/startup.sh

3 - Start Master
cd $EXISTMASTER_HOME
./bin/startup.sh

Distribute documents
1 - Login to the publisher web admin
http://localhost:8899/exist/apps/dashboard/index.html 
(admin/ )
2 - Click "eXide-XQuery IDE" 
3 - Click "New" Type "XML" Template "None" and Create
4 - Copy and Paste the xml of https://sourceforge.net/p/tinyxml/git/ci/master/tree/hamlet.xml
5 - Click "Save" 
6 - Click "mycollection"
7 - name the file "hamlet.xml" and Click Save
8 - open publisher (exist.log)

**Comment by dizzzz** [comment]
> cp -a ./build/exist-messaging-replication-0.30.3.jar ../exist/lib/extensions/.

this step is really  not required any more!   Deploying the XAAR file should just do it......

```
2018-02-05 10:53:54,614 [qtp869005911-30] INFO  (SenderConnectionFactory.java [getConnectionFactoryInstance]:66) - Connection factory: org.apache.activemq.pool.PooledConnectionFactory 
  ~[exist-messaging-replication-0.30.3.jar:?]
	at org.exist.jms.shared.send.Sender.getConnectionFactoryInstance(Sender.java:225) ~[exist-messaging-replication-0.30.3.jar:?]
	at org.exist.jms.shared.send.Sender.send(Sender.java:120) ~[exist-messaging-replication-0.30.3.jar:?]
	at org.exist.jms.replication.publish.JMSMessageSender.sendMessage(JMSMessageSender.java:82) ~[exist-messaging-replication-0.30.3.jar:?]
	at org.exist.jms.replication.publish.ReplicationTrigger.sendMessage(ReplicationTrigger.java:431) ~[exist-messaging-replication-0.30.3.jar:?]
```

this one you should have found your self. reading the logs is very important to see what is happening. From here I see that there are JAR files missing. Again, please use the XAR file, rebuilding is really not required!

> where did you get the inspiration to install this JAR file?

**Comment by ibakayoko** [comment]
Thank you for the advice.

I thought activemq-all-5.15.2.jar had all the dependencies.

I copied activemq dependencies in exist/lib/user/

```
activemq-jms-pool-5.15.2.jar
commons-pool2-2.4.2.jar
geronimo-jms_1.1_spec-1.1.1.jar
geronimo-jta_1.0.1B_spec-1.0.1.jar
slf4j-api-1.7.25.jar
```
When i delete the jar file **exist-messaging-replication-0.30.3.jar** i get an error 

When i keep the jar file **exist-messaging-replication-0.30.3.jar** the replication works.

Please what I am my missing?

Subscriber Log
[exist.log](https://github.com/eXist-db/messaging-replication/files/1699631/exist.log)

Publisher Log
[exist.log](https://github.com/eXist-db/messaging-replication/files/1699636/exist.log)

Thanks

**Comment by dizzzz** [comment]
```
2018-02-06 10:07:53,862 [main] ERROR (Configuration.java [configureStartup]:1290) - Could not find StartupTrigger class: org.exist.jms.replication.subscribe.ReceiverStartupTrigger. org.exist.jms.replication.subscribe.ReceiverStartupTrigger 
java.lang.ClassNotFoundException: org.exist.jms.replication.subscribe.ReceiverStartupTrigger
``` 

Now the jar containing the replication code is missing.

To prevent inefficient ping-ponging, please could you answer the -for me- most important question in my previous response: Why are you doing the complex copying of JAR files? It is really *not* needed, installing the XAR file via the package manager is sufficient and super simple.

The second question I asked is: what  documentation inspired you to start with these separate JAR files? I am pretty sure that I removed this text in the past (or annotated the text that it is outdated)

**Comment by ibakayoko** [comment]
I will try to find the link on which i found the instruction to copy the jar file. 

I have installed the XAR file.
But i am not sure why when i delete the JAR file I get the error.
In the previous log you see the Error when i delete the JAR.
What I am my missing?

Should i reinstall existDB from Zero?

Thanks

**Comment by dizzzz** [comment]
I did find the text, but it was clearly labeled eXist-db v2 ; there was not really a good reason apply it for exist v3.0 , which was just on top. I move the text out, but well.... it was not really needed IMO :-/

sorry, I what error did you see when you "delete the jar"? note that it is not possible to remove JAR files when a Java process is running.....

**Comment by ibakayoko** [comment]
I stopped existdb and created new instances (slave and master)

The xar is enabled (via autodeploy)

when i do not put the jar i get the error below
Slave Error
```
2018-02-07 16:07:36,588 [main] INFO  (Configuration.java [configureStartup]:1283) - Registered StartupTrigger: org.exist.repo.AutoDeploymentTrigger 
2018-02-07 16:07:36,588 [main] ERROR (Configuration.java [configureStartup]:1290) - Could not find StartupTrigger class: org.exist.jms.replication.subscribe.ReceiverStartupTrigger. org.exist.jms.replication.subscribe.ReceiverStartupTrigger 
java.lang.ClassNotFoundException: org.exist.jms.replication.subscribe.ReceiverStartupTrigger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_131]
	at org.exist.util.Configuration.configureStartup(Configuration.java:1266) [exist.jar:3.6.1]
	at org.exist.util.Configuration.configureBackend(Configuration.java:1035) [exist.jar:3.6.1]
	at org.exist.util.Configuration.<init>(Configuration.java:211) [exist.jar:3.6.1]
	at org.exist.util.SingleInstanceConfiguration.<init>(SingleInstanceConfiguration.java:57) [exist.jar:3.6.1]
	at org.exist.util.SingleInstanceConfiguration.<init>(SingleInstanceConfiguration.java:49) [exist.jar:3.6.1]
	at org.exist.jetty.JettyStart.run(JettyStart.java:162) [exist-optional.jar:3.6.1]
	at org.exist.jetty.JettyStart.main(JettyStart.java:82) [exist-optional.jar:3.6.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.exist.start.Main.invokeMain(Main.java:140) [start.jar:3.6.1]
	at org.exist.start.Main.run(Main.java:453) [start.jar:3.6.1]
	at org.exist.start.Main.main(Main.java:64) [start.jar:3.6.1]
```


Master Error
```
2018-02-07 15:50:23,916 [Thread-2] WARN  (CollectionConfiguration.java [configureTrigger]:336) - Trigger class not found: org.exist.jms.replication.publish.ReplicationTrigger 
java.lang.ClassNotFoundException: org.exist.jms.replication.publish.ReplicationTrigger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_131]
	at org.exist.collections.CollectionConfiguration.configureTrigger(CollectionConfiguration.java:309) ~[exist.jar:3.6.1]
	at org.exist.collections.CollectionConfiguration.read(CollectionConfiguration.java:148) ~[exist.jar:3.6.1]
	at org.exist.collections.CollectionConfigurationManager.loadConfiguration(CollectionConfigurationManager.java:278) ~[exist.jar:3.6.1]
	at org.exist.collections.CollectionConfigurationManager.loadAllConfigurations(CollectionConfigurationManager.java:252) ~[exist.jar:3.6.1]
	at org.exist.collections.CollectionConfigurationManager.loadAllConfigurations(CollectionConfigurationManager.java:260) ~[exist.jar:3.6.1]
	at org.exist.collections.CollectionConfigurationManager.loadAllConfigurations(CollectionConfigurationManager.java:260) ~[exist.jar:3.6.1]
	at org.exist.collections.CollectionConfigurationManager.loadAllConfigurations(CollectionConfigurationManager.java:244) ~[exist.jar:3.6.1]
	at org.exist.collections.CollectionConfigurationManager.startSystem(CollectionConfigurationManager.java:88) ~[exist.jar:3.6.1]
	at org.exist.storage.BrokerPoolServicesManager.startSystemServices(BrokerPoolServicesManager.java:184) ~[exist.jar:3.6.1]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:578) ~[exist.jar:3.6.1]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:415) ~[exist.jar:3.6.1]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:181) ~[exist.jar:3.6.1]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:110) ~[exist.jar:3.6.1]
	at org.exist.jetty.JettyStart.run(JettyStart.java:169) ~[exist-optional.jar:3.6.1]
	at org.exist.launcher.Launcher.lambda$startJetty$2(Launcher.java:165) ~[exist.jar:3.6.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2018-02-07 15:50:23,922 [Thread-2] INFO  (NativeBroker.java [sync]:3690) - Memory: 178,688K total; 1,864,192K max; 124,072K free 
```

**Comment by dizzzz** [comment]
Actually v0.30.3 has never been released ; it is work in progress. I really 'd like to recommend to use released XAR files only, and install them via the repo manager. In a clean database when doing your development.

please switch to v0.30.2 or to v0.30.4 which will be released somewhere this week (I hope)
