### ISSUE TITLE
NoSuchMethodError: XQueryContext.getRealUser()

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#25]
0.6 Version of the jar.
Due to the fact that I use the conf.xml Startup-Trigger to register the ‘callback’- function I do get the following error:

``` stacktrace
2014-03-15 13:02:28,942 [WrapperListener_start_runner] ERROR (XqueryStartupTrigger.java [executeQuery]:151) - An error occured during preparation/execution of the xquery script xmldb:exist:///db/xx/registerListener.xql: exerr:ERROR org.exist.xquery.XQueryContext.getRealUser()Lorg/exist/security/Subject; [at line 125, column 5]
In function:
        sf:registerJMSListener() [4:1:/db/xxx/xxx.xqm]
org.exist.xquery.XPathException: exerr:ERROR org.exist.xquery.XQueryContext.getRealUser()Lorg/exist/security/Subject; [at line 125, column 5]
In function:
        sf:registerJMSListener() [4:1:/db/rls/modules/sf.xqm]
        at org.exist.messaging.xquery.RegisterReceiver.eval(RegisterReceiver.java:111)
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:55)
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58)
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:65)
        at org.exist.xquery.LetExpr.eval(LetExpr.java:189)
        at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
        at org.exist.xquery.LetExpr.eval(LetExpr.java:187)
        at org.exist.xquery.BindingExpression.eval(BindingExpression.java:164)
        at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:153)
        at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:327)
        at org.exist.xquery.FunctionCall.eval(FunctionCall.java:232)
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
        at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
        at org.exist.xquery.XQuery.execute(XQuery.java:267)
        at org.exist.xquery.XQuery.execute(XQuery.java:214)
        at org.exist.xquery.XQuery.execute(XQuery.java:209)
        at org.exist.messaging.receive.XqueryStartupTrigger.executeQuery(XqueryStartupTrigger.java:142)
        at org.exist.messaging.receive.XqueryStartupTrigger.execute(XqueryStartupTrigger.java:56)
        at org.exist.storage.BrokerPool.callStartupTriggers(BrokerPool.java:1103)
        at org.exist.storage.BrokerPool.initialize(BrokerPool.java:1007)
        at org.exist.storage.BrokerPool.<init>(BrokerPool.java:725)
        at org.exist.storage.BrokerPool.configure(BrokerPool.java:248)
        at org.exist.storage.BrokerPool.configure(BrokerPool.java:224)
        at org.exist.jetty.JettyStart.run(JettyStart.java:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.exist.wrapper.Main.start(Main.java:95)
        at org.tanukisoftware.wrapper.WrapperManager$11.run(WrapperManager.java:4042)
Caused by: java.lang.NoSuchMethodError: org.exist.xquery.XQueryContext.getRealUser()Lorg/exist/security/Subject;
        at org.exist.messaging.xquery.RegisterReceiver.eval(RegisterReceiver.java:91)
        ... 31 more
```

**Comment by dizzzz** [comment]
closed
