### ISSUE TITLE
Replication: NoSuchMethodError on eXist-db 2.1

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#30]
```
java.lang.NoSuchMethodError: org.exist.storage.txn.Txn.getOriginId()Ljava/lang/String;
    at org.exist.replication.jms.publish.ReplicationTrigger.afterCreateDocument(ReplicationTrigger.java:109)
    at org.exist.collections.triggers.DocumentTriggersVisitor.afterCreateDocument(DocumentTriggersVisitor.java:84)
    at org.exist.collections.Collection.storeXMLInternal(Collection.java:1401)
    at org.exist.collections.Collection.store(Collection.java:1255)
    at org.exist.xmldb.LocalCollection.storeXMLResource(LocalCollection.java:884)
```

**Comment by dizzzz** [comment]
Fixed with #29
