### ISSUE TITLE
Abort:  Unable to determine mimetype 

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#73]
The current code in `org.exist.jms.replication.subscribe.ReplicationJmsListener#getMimeType` triggers under conditions an exception, which aborts the store/update of a document.

This is a bad thing to happen, and must be avoided

it is unclear why the code does not work OK. a debug session is required to understand.

```
2016-04-25 19:56:45,274 [ActiveMQ Session Task-13] ERROR (ReplicationJmsListener.java [onMessage]:164) - Could not handle received message: Unable to determine mimetype 
org.exist.jms.replication.subscribe.MessageReceiveException: Unable to determine mimetype
        at org.exist.jms.replication.subscribe.ReplicationJmsListener.getMimeType(ReplicationJmsListener.java:930) ~[exist-messaging-replication-0.9.6.jar:?]
        at org.exist.jms.replication.subscribe.ReplicationJmsListener.createUpdateDocument(ReplicationJmsListener.java:323) ~[exist-messaging-replication-0.9.6.jar:?]
        at org.exist.jms.replication.subscribe.ReplicationJmsListener.handleDocument(ReplicationJmsListener.java:236) ~[exist-messaging-replication-0.9.6.jar:?]
        at org.exist.jms.replication.subscribe.ReplicationJmsListener.onMessage(ReplicationJmsListener.java:144) [exist-messaging-replication-0.9.6.jar:?]
        at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.13.2.jar:5.13.2]
        at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [activemq-client-5.13.2.jar:5.13.2]
        at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [activemq-client-5.13.2.jar:5.13.2]
        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.13.2.jar:5.13.2]
        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.13.2.jar:5.13.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

**Comment by dizzzz** [comment]
fixed with https://github.com/eXist-db/messaging-replication/pull/74/commits/df5f2ac47aaba94bd2df0231f57500bd19aacb23
