### ISSUE TITLE
Mute lock stacktrace @ master

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#77]
During replication using the new `sync` sunction the following line is logged:

```
2016-05-09 21:41:32,356 [eXistThread-34] WARN  (MultiReadReentrantLock.java [releaseRead]:339) - Possible lock problem: thread eXistThread-34 released a read lock it didn't hold. Either the thread was interrupted o
r it never acquired the lock. Write lock: null 
java.lang.Throwable
        at org.exist.storage.lock.MultiReadReentrantLock.releaseRead(MultiReadReentrantLock.java:342) [eXist-db/:?]
        at org.exist.storage.lock.MultiReadReentrantLock.release(MultiReadReentrantLock.java:270) [eXist-db/:?]
        at org.exist.jms.xquery.replication.SyncResource.eval(SyncResource.java:142) [eXist-db/:?]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70) [eXist-db/:?]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [eXist-db/:?]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [eXist-db/:?]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [eXist-db/:?]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [eXist-db/:?]
        at org.exist.xquery.XQuery.execute(XQuery.java:253) [eXist-db/:?]
        at org.exist.xquery.XQuery.execute(XQuery.java:185) [eXist-db/:?]
        at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:483) [eXist-db/:?]
        at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:196) [eXist-db/:?]
```

the code 

``` java
           try (Txn txn = txnManager.beginTransaction()) {

                if (isCollection(broker, sourcePathURI)) {

                    // resource points to a collection
                    final Collection theCollection = getCollection(broker, sourcePathURI, true, false);

                    if(fullSync) {
                        trigger.afterCreateCollection(broker, txn, theCollection);
                    } else {
                        trigger.afterUpdateCollectionMetadata(broker, txn, theCollection);
                    }

                    theCollection.release(Lock.READ_LOCK);

                } else {
                    // resource points to a document
                    final DocumentImpl theDoc = getDocument(broker, parentCollectionURI, resourceURI);

                    if(fullSync) {
                        trigger.afterUpdateDocument(broker, txn, theDoc);
                    } else {
                        trigger.afterUpdateDocumentMetadata(broker, txn, theDoc);
                    }

                    theDoc.getUpdateLock().release(Lock.READ_LOCK); // here the trace is written
                }

                // Cleanup
                txn.commit();
            }

```

it looks harmless to me, but this needs some investigation/confirmation

**Comment by shabanovd** [comment]
@dizzzz note: lock release always must happen at finally block

**Comment by dizzzz** [comment]
sure (i'll fix) but that is not yet the issue here....
It logs because nothing was done with the lock it seems

the code is here: https://github.com/dizzzz/messaging-replication/blob/feature/metadata_replication/java/src/org/exist/jms/xquery/replication/SyncResource.java#L142

**Comment by shabanovd** [comment]
https://github.com/dizzzz/messaging-replication/blob/feature/metadata_replication/java/src/org/exist/jms/xquery/replication/SyncResource.java#L217 do not lock resource, so that's why there no lock

Also, this unlock very wrong https://github.com/dizzzz/messaging-replication/blob/feature/metadata_replication/java/src/org/exist/jms/xquery/replication/SyncResource.java#L219

**Comment by dizzzz** [comment]
I think I need some help from you ; I have been fighting the code for days, the current setup is the only way to get no locked-up database..... without the unlock the database just hangs.....

**Comment by dizzzz** [comment]
I did some reformatting, i think I am looking now in the wrong lines of code..... ?

**Comment by dizzzz** [comment]
trace of reformatted code: 

https://github.com/dizzzz/messaging-replication/blob/feature/metadata_replication/java/src/org/exist/jms/xquery/replication/SyncResource.java#L147 

```
2016-05-09 22:18:35,857 [eXistThread-37] WARN  (MultiReadReentrantLock.java [releaseRead]:339) - Possible lock problem: thread eXistThread-37 released a read lock it didn't hold. Either the thread was interrupted or it never acquired the lock. Write lock: null 
java.lang.Throwable
        at org.exist.storage.lock.MultiReadReentrantLock.releaseRead(MultiReadReentrantLock.java:342) [eXist-db/:?]
        at org.exist.storage.lock.MultiReadReentrantLock.release(MultiReadReentrantLock.java:270) [eXist-db/:?]
        at org.exist.jms.xquery.replication.SyncResource.eval(SyncResource.java:147) [eXist-db/:?]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70) [eXist-db/:?]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [eXist-db/:?]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [eXist-db/:?]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:267) [eXist-db/:?]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [eXist-db/:?]
        at org.exist.xquery.XQuery.execute(XQuery.java:253) [eXist-db/:?]
        at org.exist.xquery.XQuery.execute(XQuery.java:185) [eXist-db/:?]
        at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:483) [eXist-db/:?]
        at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:196) [eXist-db/:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [servlet-api-3.0.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]

```

**Comment by dizzzz** [comment]
Probably a cause is that I have no idea what is happening inside the trigger code....

**Comment by shabanovd** [comment]
@dizzzz I can do code review in 3-5 days. Can it wait?

**Comment by dizzzz** [comment]
@shabanovd yes that would be great! In the mean while I'll push out a new pre-release with a warning about this ticket.

**Comment by dizzzz** [comment]
not an issue....
