### ISSUE TITLE
Query profiling stops messaging extension

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#84]
### context
-  exist-db rc2 build 20160820
- jms messaging 0.9.10
### jms messaging and enabled query profiling
- The jms-listener is registered and working.
- In the monex app switching query profiling to enabled
- sending a jms message
- the listener does not process the message
- entry in the exist.log:

```
2016-09-07 10:51:52,323 [ActiveMQ Session Task-2] INFO  (LogFunction.java [eval]:151) - (Line: 455 /db/lib/msgListener.xqm) ==== MESSAGE RECEIVED ====
2016-09-07 10:51:52,323 [ActiveMQ Session Task-2] INFO  (LogFunction.java [eval]:151) - (Line: 457 /db/lib/msgListener.xqm) params: a=1 b=2 c=3
2016-09-07 10:51:52,323 [ActiveMQ Session Task-2] ERROR (MessagingJmsListener.java [onMessage]:173) - {5} null
```
- no further processing of the received message is done
- disabling query profiling and resending the message -> OK

**Comment by dizzzz** [comment]
@shabanovd @wolfgangmm  any idea who this could influence? copyContext?

https://github.com/eXist-db/messaging-replication/blob/12d0dc558e68f0f0a6c56851a7adf3cd2bb6504e/java/src/org/exist/jms/messaging/MessagingJmsListener.java#L173

for sure I need to extend logging here

**Comment by joewiz** [comment]
@dizzzz Wow, good find. This would definitely bite us.

**Comment by dizzzz** [comment]
thins the actual trace:

```
2016-09-11 11:17:31,515 [ActiveMQ Session Task-1] ERROR (MessagingJmsListener.java [onMessage]:173) - {1} null 
java.lang.NullPointerException
        at org.exist.xquery.Profiler.traceFunctionEnd(Profiler.java:184) ~[exist.jar:?]
        at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:312) ~[exist.jar:?]
        at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:261) ~[exist.jar:?]
        at org.exist.xquery.value.FunctionReference.evalFunction(FunctionReference.java:90) ~[exist.jar:?]
        at org.exist.jms.messaging.MessagingJmsListener.onMessage(MessagingJmsListener.java:154) [exist-messaging-replication-0.9.11.jar:?]
        at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.0.jar:5.14.0]
        at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [activemq-client-5.14.0.jar:5.14.0]
        at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [activemq-client-5.14.0.jar:5.14.0]
        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.0.jar:5.14.0]
        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.0.jar:5.14.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by dizzzz** [comment]
the code in`Profiler.java`

``` java
final String source = String.format("%s [%d:%d]", function.getContext().getSource().getKey(),
   function
   .getLine(), function.getColumn());
```

**Comment by dizzzz** [comment]
the getKey() causes the NPE , hence the 'source' is null ;  the copy context is used, this does not copy the source....

**Comment by dizzzz** [comment]
Fixed
