### ISSUE TITLE
Receiver must have state ERROR upon connection loss

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#9]
When a consumer-connection has a "Connection reset", the state of the receiver stays "STARTED".

Make the receiver go into a "ERROR' or alike mode, so it is clear in the report function the receiver is stopped.

Note that the "connection.client-id" has lost as well; in no way the receiver can be revived (expected behaviour according to documentation)

**Comment by dizzzz** [comment]
ActiveMq provides an option to set a TransportListener on a connection. https://activemq.apache.org/maven/5.8.0/apidocs/org/apache/activemq/transport/TransportListener.html

**Comment by cmisztur** [comment]
Yup.  I bounced my ActiveMQ server and both listeners still show STARTED but not processing anything.  Are re-connects possible?

/c

```
2015-09-15 12:44:14,593 [ActiveMQ Session Task-3] INFO  (MessagingJmsListener.java [onMessage]:129) - {113} Received message: messageId=ID:US09OPC50-61124-1441995804484-2:75:-1:1:10145 
2015-09-15 12:44:21,489 [ActiveMQ Connection Executor: tcp://us09opc50.maclean-fogg.com/10.37.153.202:61616@51198] ERROR (eXistMessagingListener.java [onException]:101) - java.io.EOFException 
javax.jms.JMSException: java.io.EOFException
    at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54)
    at org.apache.activemq.ActiveMQConnection.onAsyncException(ActiveMQConnection.java:1998)
    at org.apache.activemq.ActiveMQConnection.onException(ActiveMQConnection.java:2017)
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
    at org.apache.activemq.transport.ResponseCorrelator.onException(ResponseCorrelator.java:126)
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
    at org.apache.activemq.transport.WireFormatNegotiator.onException(WireFormatNegotiator.java:160)
    at org.apache.activemq.transport.AbstractInactivityMonitor.onException(AbstractInactivityMonitor.java:314)
    at org.apache.activemq.transport.TransportSupport.onException(TransportSupport.java:96)
    at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:200)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readInt(Unknown Source)
    at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:258)
    at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:221)
    at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:213)
    at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:196)
    ... 1 more
2015-09-15 12:44:21,504 [ActiveMQ Connection Executor: tcp://us09opc50.maclean-fogg.com/10.37.153.202:61616@51197] ERROR (eXistMessagingListener.java [onException]:101) - java.io.EOFException 
javax.jms.JMSException: java.io.EOFException
    at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54)
    at org.apache.activemq.ActiveMQConnection.onAsyncException(ActiveMQConnection.java:1998)
    at org.apache.activemq.ActiveMQConnection.onException(ActiveMQConnection.java:2017)
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
    at org.apache.activemq.transport.ResponseCorrelator.onException(ResponseCorrelator.java:126)
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
    at org.apache.activemq.transport.WireFormatNegotiator.onException(WireFormatNegotiator.java:160)
    at org.apache.activemq.transport.AbstractInactivityMonitor.onException(AbstractInactivityMonitor.java:314)
    at org.apache.activemq.transport.TransportSupport.onException(TransportSupport.java:96)
    at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:200)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readInt(Unknown Source)
    at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:258)
    at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:221)
    at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:213)
    at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:196)
    ... 1 more
2015-09-15 12:45:43,876 [DefaultQuartzScheduler_Worker-3] INFO  (NativeBroker.java [sync]:3588) - Memory: 507,072K total; 1,013,632K max; 306,500K free 
2015-09-15 12:45:43,876 [DefaultQuartzScheduler_Worker-3] INFO  (BTree.java [printStatistics]:2549) - dom.dbx INDEX Buffers occupation : 71% (2633 out of 3687) Cache efficiency : 100% 
2015-09-15 12:45:43,876 [DefaultQuartzScheduler_Worker-3] INFO  (DOMFile.java [printStatistics]:1360) - dom.dbx DATA Buffers occupation : 23% (58 out of 256) Cache efficiency : 99% 
2015-09-15 
```

``` xml
<Receiver id="114">
<state>STARTED</state>
<java.naming.factory.initial>org.apache.activemq.jndi.ActiveMQInitialContextFactory</java.naming.factory.initial>
<java.naming.provider.url>tcp://us09opc50.maclean-fogg.com:61616</java.naming.provider.url>
<connection-factory>ConnectionFactory</connection-factory>
<destination>dynamicTopics/controllino.devices.MACLEANFOGG.001EC0049FF3</destination>
<usage>messaging</usage>
<errorMessages>
<error src="connection" timestamp="2015-09-15T12:44:21-05:00" exception="JMSException">java.io.EOFException</error>
</errorMessages>
<statistics>
<nrProcessedMessages>5</nrProcessedMessages>
<cumulativeProcessingTime>PT0.451S</cumulativeProcessingTime>
<nrFailedMessages>0</nrFailedMessages>
</statistics>
</Receiver>
<Receiver id="113">
<state>STARTED</state>
<java.naming.factory.initial>org.apache.activemq.jndi.ActiveMQInitialContextFactory</java.naming.factory.initial>
<java.naming.provider.url>tcp://us09opc50.maclean-fogg.com:61616</java.naming.provider.url>
<connection-factory>ConnectionFactory</connection-factory>
<destination>dynamicTopics/controllino.advisory</destination>
<usage>messaging</usage>
<errorMessages>
<error src="connection" timestamp="2015-09-15T12:44:21-05:00" exception="JMSException">java.io.EOFException</error>
</errorMessages>
<statistics>
<nrProcessedMessages>9172</nrProcessedMessages>
<cumulativeProcessingTime>PT4M54.370S</cumulativeProcessingTime>
<nrFailedMessages>0</nrFailedMessages>
</statistics>
</Receiver>
```

**Comment by dizzzz** [comment]
yes, that is possible: https://github.com/eXist-db/messaging-replication/wiki/Tips-&-Tricks-&-Tweaks#auto-reconnect

**Comment by cmisztur** [comment]
```
"java.naming.provider.url" := "failover:tcp://host:61616"
```

like that?

**Comment by dizzzz** [comment]
Yes, that should be correct; more on `http://activemq.apache.org/failover-transport-reference.html` : 

e.g. `failover:(tcp://localhost:61616,tcp://remotehost:61616)`

**Comment by dizzzz** [comment]
updated the wiki, thnx

**Comment by cmisztur** [comment]
Yup, that fixes the JMS listener from dying.  I am wondering if I could ever again get an EOF exception if the MQ broker shutdown is timed right.

**Comment by dizzzz** [comment]
pooh, i could not say; this issue at least would implement a correct close of connection when required
