### ISSUE TITLE
Actual error is not visible when sending a message

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#92]
The second time running the example of http://localhost:8080/exist/apps/messaging-replication/messaging-send.html (10 messages) the following error appears:

```
2016-11-04 20:39:56,419 [qtp362432678-39] ERROR (Sender.java [send]:177) - javax.jms.JMSException: Error while attempting to add new Connection to the pool 
2016-11-04 20:39:56,420 [qtp362432678-39] ERROR (SendMessage.java [eval]:90) - exerr:ERROR Error while attempting to add new Connection to the pool 
```

this must be introduced in an attempt to re-use connections,.

**Comment by dizzzz** [comment]
actually it was a misconfiguration; a wrong hostname, but the root cause is not visible

```
2016-11-04 21:22:10,611 [qtp362432678-166] INFO  (SenderConnectionFactory.java [getConnectionFactoryInstance]:59) - Creating new connection factory for tcp://miniserver.locall:61616 
2016-11-04 21:22:10,611 [qtp362432678-166] INFO  (SenderConnectionFactory.java [getConnectionFactoryInstance]:66) - Connection factory: org.apache.activemq.pool.PooledConnectionFactory 
2016-11-04 21:22:10,636 [qtp362432678-166] ERROR (Sender.java [send]:177) - Error while attempting to add new Connection to the pool 
javax.jms.JMSException: Error while attempting to add new Connection to the pool
        at org.apache.activemq.jms.pool.PooledConnectionFactory.createJmsException(PooledConnectionFactory.java:266) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:225) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:204) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.exist.jms.send.Sender.send(Sender.java:130) [exist-messaging-replication-0.9.13.jar:?]
        at org.exist.jms.xquery.messaging.SendMessage.eval(SendMessage.java:87) [exist-messaging-replication-0.9.13.jar:?]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73) [exist.jar:?]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [exist.jar:?]
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:?]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:?]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
        at org.exist.xquery.ForExpr.processItem(ForExpr.java:239) [exist.jar:?]
        at org.exist.xquery.ForExpr.eval(ForExpr.java:179) [exist.jar:?]
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:?]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:?]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:?]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:?]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:?]
        at org.exist.xquery.XQuery.execute(XQuery.java:253) [exist.jar:?]
        at org.exist.xquery.XQuery.execute(XQuery.java:185) [exist.jar:?]
        at org.exist.http.servlets.XQueryServlet.process(XQueryServlet.java:483) [exist-optional.jar:?]
        at org.exist.http.servlets.XQueryServlet.doPost(XQueryServlet.java:196) [exist-optional.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [servlet-api-3.1.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:159) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:?]
        at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:545) [exist-optional.jar:?]
....
Caused by: javax.jms.JMSException: Could not connect to broker URL: tcp://miniserver.locall:61616. Reason: java.net.UnknownHostException: miniserver.locall
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:374) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:275) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.apache.activemq.jms.pool.PooledConnectionFactory$1.makeObject(PooledConnectionFactory.java:95) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.apache.activemq.jms.pool.PooledConnectionFactory$1.makeObject(PooledConnectionFactory.java:92) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1041) ~[commons-pool2-2.4.2.jar:2.4.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1221) ~[commons-pool2-2.4.2.jar:2.4.2]
        at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:221) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        ... 67 more
Caused by: java.net.UnknownHostException: miniserver.locall
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_111]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_111]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_111]
        at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:168) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:354) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244) ~[activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:275) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.apache.activemq.jms.pool.PooledConnectionFactory$1.makeObject(PooledConnectionFactory.java:95) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.apache.activemq.jms.pool.PooledConnectionFactory$1.makeObject(PooledConnectionFactory.java:92) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1041) ~[commons-pool2-2.4.2.jar:2.4.2]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1221) ~[commons-pool2-2.4.2.jar:2.4.2]
        at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:221) ~[activemq-jms-pool-5.14.1.jar:5.14.1]
        ... 67 more
2016-11-04 21:22:10,638 [qtp362432678-166] ERROR (SendMessage.java [eval]:90) - exerr:ERROR Error while attempting to add new Connection to the pool 
```
