### ISSUE TITLE
'No SessionManager' error when receiving messages

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#93]
It appears when in the callback function the eval function is used:

```xquery
declare function local:handleMessage($content as item(), $params as item()*, 
                            $messageProperties as map(), $jmsConfig as map() )
{
    util:eval("count(collection(/db))")
};
```

the following trace appears:

```
2016-11-05 18:44:20,429 [ActiveMQ Session Task-2] ERROR (MessagingJmsListener.java [onMessage]:174) - No SessionManager (Receiver=3) 
java.lang.IllegalStateException: No SessionManager
        at org.eclipse.jetty.server.Request.getSession(Request.java:1511) ~[jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at org.eclipse.jetty.server.Request.getSession(Request.java:1486) ~[jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:279) ~[servlet-api-3.1.jar:3.1.0]
        at org.exist.http.servlets.HttpRequestWrapper.getSession(HttpRequestWrapper.java:671) ~[exist-optional.jar:?]
        at org.exist.xquery.XQueryContext.getUserFromHttpSession(XQueryContext.java:2179) ~[exist.jar:?]
        at org.exist.xquery.XQueryContext.prepareForExecution(XQueryContext.java:530) ~[exist.jar:?]
        at org.exist.xquery.XQuery.execute(XQuery.java:220) ~[exist.jar:?]
        at org.exist.xquery.XQuery.execute(XQuery.java:194) ~[exist.jar:?]
        at org.exist.xquery.functions.util.Eval.execute(Eval.java:435) ~[exist.jar:?]
        at org.exist.xquery.functions.util.Eval.doEval(Eval.java:389) ~[exist.jar:?]
        at org.exist.xquery.functions.util.Eval.eval(Eval.java:225) ~[exist.jar:?]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:73) ~[exist.jar:?]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) ~[exist.jar:?]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:?]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) ~[exist.jar:?]
        at org.exist.xquery.SequenceConstructor.eval(SequenceConstructor.java:84) ~[exist.jar:?]
        at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:155) ~[exist.jar:?]
        at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:302) ~[exist.jar:?]
        at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:261) ~[exist.jar:?]
        at org.exist.xquery.value.FunctionReference.evalFunction(FunctionReference.java:90) ~[exist.jar:?]
        at org.exist.jms.messaging.MessagingJmsListener.onMessage(MessagingJmsListener.java:152) [exist-messaging-replication-0.9.13.jar:?]
        at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.1.jar:5.14.1]
        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.1.jar:5.14.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by dizzzz** [comment]
hmmm checking jetty's code:

http://download.eclipse.org/jetty/stable-9/xref/org/eclipse/jetty/server/Request.html#1526

a jetty session manager is actually missing. hmmmm;

Adam suggests that there is a problem in the XQueryContext cloning (where we had an issue before)

**Comment by dizzzz** [comment]
in org.exist.xquery.XQueryContext#getUserFromHttpSession line 2149 it should be possible that -when the Request module is removed- the piece of code that causes the issue, is never called. 

unfortunately the following line

``` java
xqueryContext.setModule(RequestModule.NAMESPACE_URI, null);
```

does not seem to be active for the xquery util:eval function
